##
##      To build the AI_SADTALKER_ docker image
##

# base stuff
FROM yeepeekoo/public:ai_base_osais

## sad talker requirements

RUN pip3 install \
    gradio \
    gfpgan \
    av \
    safetensors

RUN pip3 install \
    numpy==1.23.4 \
    face_alignment==1.3.5 \
    imageio==2.19.3 \
    imageio-ffmpeg==0.4.7 

RUN pip3 install \
    librosa==0.9.2 \ 
    numba \
    resampy==0.3.1 \
    pydub==0.25.1  \
    scipy==1.10.1 \
    kornia==0.6.8 
    
RUN pip3 install \
    tqdm \
    yacs==0.1.8 \
    pyyaml  \
    joblib==1.1.0 
    
RUN pip3 install \
    scikit-image==0.19.3 \
    basicsr==1.4.2 \
    facexlib==0.3.0

# run as a server
CMD ["uvicorn", "main_fastapi:app", "--host", "0.0.0.0", "--port", "5000"]
